### ISSUE TITLE
get_palette_split() is not a member of SpatialEditor

### ISSUE THREAD

**Issue by ghost** [Relintai/voxelman#4]
SpatialEditor does not contain get_palette_split() . Maybe is Godot 4 api?

modules\voxel\world\voxel_world_editor.cpp(334): error C2039: 'get_palette_split': is not a member of 'SpatialEditor'
modules\voxel\world\voxel_world_editor.cpp(337): error C2039: 'get_palette_split': is not a member of 'SpatialEditor'

**Comment by Relintai** [comment]
It's a recent 3.x (and also 4.0) commit. Same change is needed as here: https://github.com/Relintai/terraman/commit/2aa31ea22ed3a39c07307d3598c2fc084b4a31e3

Thanks for reporting it, I will fix it soon.

I'll also fix compile for current 4.0 master, as it has been already due for a while. (I think it's already at a release candidate state.)
