### ISSUE TITLE
Proposal to rename Voxelman to Voxel

### ISSUE THREAD

**Issue by ghost** [Relintai/voxelman#5]
I'm testing this out right now. Thank you for the work and making this available for us to use.

I would like to propose changing Voxelman to Voxel or VOXELMAN to VOXEL. Seems like a strange name Voxelman. If anything it makes it less clear that this is a voxel module. I originally thought of voxel characters or models creator (ie makes voxel men) rather than a minecraft type voxelized world. 

So i went ahead and renamed it that way . Looks neater from within Godot more in line with the naming convention of all other tools 
![image](https://user-images.githubusercontent.com/36826319/152679945-9a2b242a-6ddf-4dc5-86fe-63b8fd27009d.png)

![image](https://user-images.githubusercontent.com/36826319/152680031-f9755563-71e2-4e56-8b36-b353fb162af1.png)

I had to rename VoxelmanLight to PropVoxelLight which is closer to what it actually is , a voxel light prop. Feel free to close this but I think both this module and the terrain one should be renamed to somethin more sensible Voxel and Terrain . Simple. 

Either way been testing it more and is pretty fun. It has a numbr of issues I identified tho. Thank you for this!

**Comment by Relintai** [comment]
Originally I did not want to name the module just voxel as then you need to name the directory like that in godot/modules.
I thought that's probably a bad idea as it's a way too generic name, so I was like it's a voxel manager so... I kind of ended up calling it just voxelman.

About the classes I named them like that so I don't have name collisions with https://github.com/Zylann/godot_voxel if they ever get compiled together. (I actually had it like that during early development, as I was worried for a long time that doing this from scratch is a bad idea. - Which it is. - But reworking Zylann's module would have probably taken just as much time and effort, so I guess I just did this bad idea.)

It definitely looks better how it's like on your pic. I'll rethink whether having compatibility with other voxel stuff is worth having over those class names.

I don't think I'll go for the module rename though. At least not for just voxel. (Even thought it's probably a good idea.)

**Comment by ghost** [comment]
I agree that you should not rename the module or project just some of the user facing classes. Just looks more clean and closer to what Godot's nodes would have been named had they implemented voxel specific nodes.
 
I don't think you need to worry about people using Zylan's godot_voxel and your voxel module at the same time. Both modules have their own setup and don't interact with one another.  Users would have to choose. In fact I did just that and went with your voxel module because is simpler, more flexible and extensible via your other modules.  

I am testing this Voxel module and ThreadPool in my custom Godot build  for personal use see [this](https://github.com/goblinengine/goblin) repo and [CHANGELOG](https://github.com/goblinengine/goblin/blob/main/CHANGELOG.md) . Is mostly for personal use or for anyone that's interested in using it. Let me know if there's anything specifically you need testing.

**Comment by Relintai** [comment]
I thought about it more. I'll do it. Probably after I'm finished with fixing the compile for 4.0. 
I also wanted to port the per chunk material support for a while now from Terraman, and I wanted to update the demonstration project too. So I guess it would be a good time to quickly get all of these done.

I might also do the same change to Terraman, the nodes there will probably look better this way aswell. Except with a Terrain prefix.

> I am testing [this](https://github.com/goblinengine/goblin) Voxel module and ThreadPool in my custom Godot build for personal use see this repo and [CHANGELOG](https://github.com/goblinengine/goblin/blob/main/CHANGELOG.md) . Is mostly for personal use or for anyone that's interested in using it.

It looks pretty cool. I might grab some of the stuff from it for my godot fork.

> Let me know if there's anything specifically you need testing.

I don't have anything specific, as I test the code that I'm working on. Where I usually have issues is when I break something that I don't expect, and of course bad UX is sometimes hard to notice on super complex stuff (like this module).

So if you run into something that's broken just reporting it should be enough. Especially for this module, as currently I'm mostly working with Terraman (which is this module converted to a terrain engine).

**Comment by ghost** [comment]
Sounds good!!

Also you're welcome to grab whatever you want from my custom build is all MIT. I borrowed some things from Goost also and contributed back to Goost too 😁 Also [here](https://github.com/goblinengine/goblin/actions) you can find builds with these features already implemented ready to go. You might wanna try it out see how some of these features work out.
